baseurl = "https://kknnkknn.github.io/blog/"
publishDir = "docs"
title = "___"
theme = "coder"
languagecode = "ja"
defaultcontentlanguage = "ja"

paginate = 20
colorScheme = "auto"

[services]
[services.disqus]

[markup.highlight]
style = "github-dark"

[params]
  author = "nk"
  info = ""
  dateFormat = "2006-01-02"
  description = "Personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/images/icon_500.PNG"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/imges/icon.svg"
  favicon_16 = "/imges/favicon.ico"
  favicon_32 = "/imges/favicon.ico"
  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/kknnkknn/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/article/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
