baseurl = "https://krnk0.github.io/blog/"
publishDir = "public"
#title = "blog"
theme = "minimal"
languagecode = "ja"
defaultcontentlanguage = "ja"

paginate = 20
colorScheme = "auto"

[services]
  [services.googleAnalytics]
    ID = 'G-EM72XSTWPY'
[services.disqus]

[markup.highlight]
style = "github-dark"

[params]
  author = "nk"
  info = ""
  dateFormat = "2006-01-02"
  description = "Personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/icon_500.PNG"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/images/icon.svg"
  favicon_16 = "/images/favicon.ico"
  favicon_32 = "/images/favicon.ico"
  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/krnk0/"

# Menu links
[[menu.main]]
  name = "Article"
  weight = 20
  url  = "article/"
[[menu.main]]
  name = "About"
  weight = 20
  url = "about/"
