name: github pages   # ← 好きな名前でOK

on:
  push:
    branches:
      - source       # source ブランチに push されたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: source            # 明示しておくと安心
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
